# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
