# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0002_eventtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 5, 10, 22, 12, 29, 257293, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
